name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Load Firebase config
        run: |
          echo "$FIREBASE_CONFIG" > config/firebaseConfig.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      - run: npm run test
